In [ ]:
import numpy
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras.layers import Conv2D
from keras.optimizers import Adam
from keras.utils import np_utils
Loading the data

(X_train,y_train),(X_test,y_test)=mnist.load_data()
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 0s 0us/step
print(X_train.shape)
print(X_test.shape)
(60000, 28, 28)
(10000, 28, 28)
Analyzing the data

X_train[0]
array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 253, 253, 212, 135, 132,  16,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0]], dtype=uint8)
y_train[0]
5
import matplotlib.pyplot as plt
plt.imshow(X_train[0])

Reshaping the data

X_train=X_train.reshape(60000,28,28,1).astype('float32')
X_test=X_test.reshape(10000,28,28,1).astype('float32')
Applying one hot encoding

number_of_classes=10
y_train=np_utils.to_categorical(y_train,number_of_classes)
y_test=np_utils.to_categorical(y_test,number_of_classes)
y_train[0]
array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)
Adding CNN layers

model=Sequential()
model.add(Conv2D(64,(3,3),input_shape=(28,28,1),activation='relu'))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(Flatten())
model.add(Dense(number_of_classes,activation='softmax'))
Compiling the model

model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])
Train the model

model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5,batch_size=32)
Epoch 1/5
1875/1875 [==============================] - 188s 100ms/step - loss: 0.2267 - accuracy: 0.9520 - val_loss: 0.0715 - val_accuracy: 0.9773
Epoch 2/5
1875/1875 [==============================] - 184s 98ms/step - loss: 0.0663 - accuracy: 0.9798 - val_loss: 0.0820 - val_accuracy: 0.9765
Epoch 3/5
1875/1875 [==============================] - 181s 97ms/step - loss: 0.0447 - accuracy: 0.9857 - val_loss: 0.0841 - val_accuracy: 0.9764
Epoch 4/5
1875/1875 [==============================] - 185s 98ms/step - loss: 0.0326 - accuracy: 0.9897 - val_loss: 0.0932 - val_accuracy: 0.9773
Epoch 5/5
1875/1875 [==============================] - 185s 98ms/step - loss: 0.0268 - accuracy: 0.9912 - val_loss: 0.1147 - val_accuracy: 0.9756
Observing the metrices

metrics=model.evaluate(X_test,y_test,verbose=0)
print("Metrics(Test loss & Test Accuracy):")
print(metrics)
Metrics(Test loss & Test Accuracy):
[0.11473851650953293, 0.975600004196167]
Test the model

prediction=model.predict(X_test[:4])
print(prediction)
1/1 [==============================] - 0s 101ms/step
[[1.3074227e-13 1.7454416e-21 5.3435435e-13 1.7902497e-12 4.0979252e-22
  2.8972004e-20 7.2950227e-26 1.0000000e+00 4.7924002e-16 3.3929484e-14]
 [9.7674950e-12 3.3886529e-11 1.0000000e+00 5.7173667e-13 3.8048021e-18
  5.7850559e-18 1.8595079e-11 1.9510378e-23 1.7745634e-16 1.4665846e-19]
 [4.2670916e-09 9.9996543e-01 3.4394697e-07 3.6487033e-12 2.1101288e-05
  9.8433119e-08 2.9256157e-08 1.2647420e-05 3.6793017e-07 2.0908446e-14]
 [1.0000000e+00 1.7292669e-14 1.5496912e-10 3.9331251e-15 1.7032449e-12
  7.0154711e-12 9.5852233e-09 1.9213345e-13 2.4322634e-12 2.8453442e-09]]
import numpy as np
print(np.argmax(prediction,axis=1))
print(y_test[:4])
[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Observing the metrices

metrics=model.evaluate(X_test,y_test,verbose=0)
print("Metrics(Test loss & Test Accuracy):")
print(metrics)
Metrics(Test loss & Test Accuracy):
[0.11473851650953293, 0.975600004196167]
Test the model

prediction=model.predict(X_test[:4])
print(prediction)
1/1 [==============================] - 0s 23ms/step
[[1.3074227e-13 1.7454416e-21 5.3435435e-13 1.7902497e-12 4.0979252e-22
  2.8972004e-20 7.2950227e-26 1.0000000e+00 4.7924002e-16 3.3929484e-14]
 [9.7674950e-12 3.3886529e-11 1.0000000e+00 5.7173667e-13 3.8048021e-18
  5.7850559e-18 1.8595079e-11 1.9510378e-23 1.7745634e-16 1.4665846e-19]
 [4.2670916e-09 9.9996543e-01 3.4394697e-07 3.6487033e-12 2.1101288e-05
  9.8433119e-08 2.9256157e-08 1.2647420e-05 3.6793017e-07 2.0908446e-14]
 [1.0000000e+00 1.7292669e-14 1.5496912e-10 3.9331251e-15 1.7032449e-12
  7.0154711e-12 9.5852233e-09 1.9213345e-13 2.4322634e-12 2.8453442e-09]]
import numpy as np
print(np.argmax(prediction,axis=1))
print(y_test[:4])
[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Save the model

model.save('models/mnistCNN.h5')
Test with saved model

from keras.datasets import mnist
from matplotlib import pyplot
(X_train,y_train),(X_test,y_test)=mnist.load_data()
print('X_train:' +str(X_train.shape))
print('y_train:' +str(y_train.shape))
print('X_test:' +str(X_test.shape))
print('y_test:' +str(y_test.shape))
from matplotlib import pyplot
for i in range(9):
  pyplot.subplot(330+1+i)
  pyplot.imshow(X_train[i],cmap=pyplot.get_cmap('gray'))
  pyplot.show()
X_train:(60000, 28, 28)
y_train:(60000,)
X_test:(10000, 28, 28)
y_test:(10000,)








