In [ ]:
import numpy as np
import tensorflow as tf
from keras.datasets import mnist
from keras.models import Sequential
from keras import layers
from keras.layers import Dense,Flatten
from keras.layers import Conv2D
from keras.optimizers import Adam
from keras.utils import np_utils
import matplotlib.pyplot as plt
from keras.callbacks import EarlyStopping, ReduceLROnPlateau
(X_train,y_train),(X_test,y_test) =mnist.load_data()
print(X_train.shape)
print(X_test.shape)
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(10000, 28, 28)
print("The label value is ",y_test[21])
plt.imshow(X_test[21])
The label value is  6

print("The label value is ",y_train[24])
plt.imshow(X_train[24])
The label value is  1

X_train = X_train.reshape(60000, 28, 28, 1).astype('float32')
X_test = X_test.reshape(10000, 28, 28, 1).astype('float32')
number_of_classes= 10
y_train = np_utils.to_categorical(y_train,number_of_classes)
y_test = np_utils.to_categorical(y_test,number_of_classes)
print("After encoding the value 6 of y_test[21] become", y_test[21])
After encoding the value 6 of y_test[21] become [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
model= tf.keras.Sequential()
model.add(Conv2D(64,(3,3),input_shape=(28,28,1),activation='relu'))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(Flatten())
model.add(Dense(number_of_classes,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer="Adam", metrics=['accuracy'])
early_stopping = EarlyStopping(monitor='accuracy',
                        patience=3)
reduce_lr = ReduceLROnPlateau(monitor='accuracy',
                        patience=3,
                        factor=0.5,min_lr=0.00001)

callback = [reduce_lr,early_stopping]
model.fit(X_train, y_train, validation_data=(X_test, y_test),epochs=15,batch_size=32,callbacks=callback)
Epoch 1/15
1875/1875 [==============================] - 174s 93ms/step - loss: 0.1186 - accuracy: 0.9666 - val_loss: 0.0951 - val_accuracy: 0.9736 - lr: 0.0010
Epoch 2/15
1875/1875 [==============================] - 172s 92ms/step - loss: 0.0591 - accuracy: 0.9820 - val_loss: 0.0826 - val_accuracy: 0.9779 - lr: 0.0010
Epoch 3/15
1875/1875 [==============================] - 176s 94ms/step - loss: 0.0440 - accuracy: 0.9860 - val_loss: 0.1151 - val_accuracy: 0.9695 - lr: 0.0010
Epoch 4/15
1875/1875 [==============================] - 176s 94ms/step - loss: 0.0342 - accuracy: 0.9889 - val_loss: 0.0950 - val_accuracy: 0.9766 - lr: 0.0010
Epoch 5/15
1875/1875 [==============================] - 181s 97ms/step - loss: 0.0245 - accuracy: 0.9927 - val_loss: 0.0783 - val_accuracy: 0.9811 - lr: 0.0010
Epoch 6/15
1875/1875 [==============================] - 178s 95ms/step - loss: 0.0257 - accuracy: 0.9928 - val_loss: 0.0970 - val_accuracy: 0.9799 - lr: 0.0010
Epoch 7/15
1875/1875 [==============================] - 172s 92ms/step - loss: 0.0198 - accuracy: 0.9945 - val_loss: 0.1459 - val_accuracy: 0.9779 - lr: 0.0010
Epoch 8/15
1875/1875 [==============================] - 178s 95ms/step - loss: 0.0195 - accuracy: 0.9947 - val_loss: 0.1139 - val_accuracy: 0.9809 - lr: 0.0010
Epoch 9/15
1875/1875 [==============================] - 173s 92ms/step - loss: 0.0175 - accuracy: 0.9955 - val_loss: 0.1384 - val_accuracy: 0.9800 - lr: 0.0010
Epoch 10/15
1875/1875 [==============================] - 176s 94ms/step - loss: 0.0164 - accuracy: 0.9960 - val_loss: 0.1461 - val_accuracy: 0.9804 - lr: 0.0010
Epoch 11/15
1875/1875 [==============================] - 173s 92ms/step - loss: 0.0146 - accuracy: 0.9967 - val_loss: 0.2218 - val_accuracy: 0.9768 - lr: 0.0010
Epoch 12/15
1875/1875 [==============================] - 175s 93ms/step - loss: 0.0183 - accuracy: 0.9964 - val_loss: 0.2677 - val_accuracy: 0.9753 - lr: 0.0010
Epoch 13/15
1875/1875 [==============================] - 173s 92ms/step - loss: 0.0156 - accuracy: 0.9969 - val_loss: 0.2262 - val_accuracy: 0.9781 - lr: 0.0010
Epoch 14/15
1875/1875 [==============================] - 176s 94ms/step - loss: 0.0138 - accuracy: 0.9969 - val_loss: 0.2325 - val_accuracy: 0.9815 - lr: 0.0010
Epoch 15/15
1875/1875 [==============================] - 173s 93ms/step - loss: 0.0130 - accuracy: 0.9975 - val_loss: 0.3288 - val_accuracy: 0.9778 - lr: 0.0010
metrics=model.evaluate(X_test,y_test,verbose=0)
print("loss & accuracy")
print(metrics)
loss & accuracy
[0.3288283348083496, 0.9778000116348267]
prediction=model.predict(X_test[:4])
print(np.argmax(prediction,axis=1))
print(y_test[:4])
1/1 [==============================] - 0s 94ms/step
[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
model.save('digit-recognition.h5')
!tar -zcvf digit-recognition.tar digit-recognition.h5
digit-recognition.h5
!pip install ibm_watson_machine_learning
!pip install watson-machine-learning-client
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ibm_watson_machine_learning
  Downloading ibm_watson_machine_learning-1.0.256-py3-none-any.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 8.5 MB/s 
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from ibm_watson_machine_learning) (4.13.0)
Collecting ibm-cos-sdk==2.7.*
  Downloading ibm-cos-sdk-2.7.0.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 946 kB/s 
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from ibm_watson_machine_learning) (1.24.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from ibm_watson_machine_learning) (21.3)
Requirement already satisfied: pandas<1.5.0,>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from ibm_watson_machine_learning) (1.3.5)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from ibm_watson_machine_learning) (2022.9.24)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from ibm_watson_machine_learning) (2.23.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from ibm_watson_machine_learning) (0.8.10)
Collecting lomond
  Downloading lomond-0.3.3-py2.py3-none-any.whl (35 kB)
Collecting ibm-cos-sdk-core==2.7.0
  Downloading ibm-cos-sdk-core-2.7.0.tar.gz (824 kB)
     |████████████████████████████████| 824 kB 55.9 MB/s 
Collecting ibm-cos-sdk-s3transfer==2.7.0
  Downloading ibm-cos-sdk-s3transfer-2.7.0.tar.gz (133 kB)
     |████████████████████████████████| 133 kB 54.6 MB/s 
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting docutils<0.16,>=0.10
  Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
     |████████████████████████████████| 547 kB 54.9 MB/s 
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.7/dist-packages (from ibm-cos-sdk-core==2.7.0->ibm-cos-sdk==2.7.*->ibm_watson_machine_learning) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas<1.5.0,>=0.24.2->ibm_watson_machine_learning) (2022.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas<1.5.0,>=0.24.2->ibm_watson_machine_learning) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil<3.0.0,>=2.1->ibm-cos-sdk-core==2.7.0->ibm-cos-sdk==2.7.*->ibm_watson_machine_learning) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->ibm_watson_machine_learning) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->ibm_watson_machine_learning) (2.10)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->ibm_watson_machine_learning) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->ibm_watson_machine_learning) (3.9.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->ibm_watson_machine_learning) (3.0.9)
Building wheels for collected packages: ibm-cos-sdk, ibm-cos-sdk-core, ibm-cos-sdk-s3transfer
  Building wheel for ibm-cos-sdk (setup.py) ... done
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.7.0-py2.py3-none-any.whl size=72564 sha256=42d0da6c0617df5e956bb0d07bd02c58d37a84a7a68352e9deaf3ddf40b01f9e
  Stored in directory: /root/.cache/pip/wheels/47/22/bf/e1154ff0f5de93cc477acd0ca69abfbb8b799c5b28a66b44c2
  Building wheel for ibm-cos-sdk-core (setup.py) ... done
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.7.0-py2.py3-none-any.whl size=501013 sha256=fb956dbe1ccf2003a594b846988f62c71e6e063afe7a1e5faefeca50b22c4395
  Stored in directory: /root/.cache/pip/wheels/6c/a2/e4/c16d02f809a3ea998e17cfd02c13369281f3d232aaf5902c19
  Building wheel for ibm-cos-sdk-s3transfer (setup.py) ... done
  Created wheel for ibm-cos-sdk-s3transfer: filename=ibm_cos_sdk_s3transfer-2.7.0-py2.py3-none-any.whl size=88619 sha256=400b462e642a953bd94f160fbc7f8e77717bbcf3f2d22fc3d855e4dbce05a7be
  Stored in directory: /root/.cache/pip/wheels/5f/b7/14/fbe02bc1ef1af890650c7e51743d1c83890852e598d164b9da
Successfully built ibm-cos-sdk ibm-cos-sdk-core ibm-cos-sdk-s3transfer
Installing collected packages: jmespath, docutils, ibm-cos-sdk-core, ibm-cos-sdk-s3transfer, lomond, ibm-cos-sdk, ibm-watson-machine-learning
  Attempting uninstall: docutils
    Found existing installation: docutils 0.17.1
    Uninstalling docutils-0.17.1:
      Successfully uninstalled docutils-0.17.1
Successfully installed docutils-0.15.2 ibm-cos-sdk-2.7.0 ibm-cos-sdk-core-2.7.0 ibm-cos-sdk-s3transfer-2.7.0 ibm-watson-machine-learning-1.0.256 jmespath-0.10.0 lomond-0.3.3
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting watson-machine-learning-client
  Downloading watson_machine_learning_client-1.0.391-py3-none-any.whl (538 kB)
     |████████████████████████████████| 538 kB 6.5 MB/s 
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from watson-machine-learning-client) (4.64.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from watson-machine-learning-client) (1.24.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from watson-machine-learning-client) (2.23.0)
Requirement already satisfied: lomond in /usr/local/lib/python3.7/dist-packages (from watson-machine-learning-client) (0.3.3)
Requirement already satisfied: ibm-cos-sdk in /usr/local/lib/python3.7/dist-packages (from watson-machine-learning-client) (2.7.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from watson-machine-learning-client) (0.8.10)
Collecting boto3
  Downloading boto3-1.25.4-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 58.5 MB/s 
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from watson-machine-learning-client) (2022.9.24)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from watson-machine-learning-client) (1.3.5)
Collecting s3transfer<0.7.0,>=0.6.0
  Downloading s3transfer-0.6.0-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 3.3 MB/s 
Collecting botocore<1.29.0,>=1.28.4
  Downloading botocore-1.28.4-py3-none-any.whl (9.3 MB)
     |████████████████████████████████| 9.3 MB 63.0 MB/s 
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.7/dist-packages (from boto3->watson-machine-learning-client) (0.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.7/dist-packages (from botocore<1.29.0,>=1.28.4->boto3->watson-machine-learning-client) (2.8.2)
Collecting urllib3
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 72.0 MB/s 
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.29.0,>=1.28.4->boto3->watson-machine-learning-client) (1.15.0)
Requirement already satisfied: ibm-cos-sdk-core==2.7.0 in /usr/local/lib/python3.7/dist-packages (from ibm-cos-sdk->watson-machine-learning-client) (2.7.0)
Requirement already satisfied: ibm-cos-sdk-s3transfer==2.7.0 in /usr/local/lib/python3.7/dist-packages (from ibm-cos-sdk->watson-machine-learning-client) (2.7.0)
Requirement already satisfied: docutils<0.16,>=0.10 in /usr/local/lib/python3.7/dist-packages (from ibm-cos-sdk-core==2.7.0->ibm-cos-sdk->watson-machine-learning-client) (0.15.2)
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 71.4 MB/s 
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->watson-machine-learning-client) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->watson-machine-learning-client) (3.0.4)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->watson-machine-learning-client) (2022.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->watson-machine-learning-client) (1.21.6)
Installing collected packages: urllib3, botocore, s3transfer, boto3, watson-machine-learning-client
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
Successfully installed boto3-1.25.4 botocore-1.28.4 s3transfer-0.6.0 urllib3-1.25.11 watson-machine-learning-client-1.0.391
from ibm_watson_machine_learning import APIClient
credentials ={
    "url":"https://us-south.ml.cloud.ibm.com",
    "apikey":"mXnZA6alXjP7nBHb2MhUPvhXgLMo3f9rrj094TbXWv44"
}
client = APIClient(credentials)
client
Python 3.7 and 3.8 frameworks are deprecated and will be removed in a future release. Use Python 3.9 framework instead.
client.spaces.get_details()
{'resources': [{'entity': {'compute': [{'crn': 'crn:v1:bluemix:public:pm-20:us-south:a/cec083d33451444c9bdfbd8a8e68291d:db32e8a0-571b-456d-bfb7-b83d8e756301::',
      'guid': 'db32e8a0-571b-456d-bfb7-b83d8e756301',
      'name': 'Watson Machine Learning-uu',
      'type': 'machine_learning'}],
    'description': '',
    'name': 'Digit Recognition Deploy',
    'scope': {'bss_account_id': 'cec083d33451444c9bdfbd8a8e68291d'},
    'stage': {'production': False},
    'status': {'state': 'active'},
    'storage': {'properties': {'bucket_name': '309ed175-951a-4207-ad64-06cb7532d89e',
      'bucket_region': 'us-south',
      'credentials': {'admin': {'access_key_id': 'b8d969e17ac94bba9e5796898ad55bdd',
        'api_key': 'YOIs8ACBZPHx_YJnMIkItYHteMz6leUrSBQcVZcllU-F',
        'secret_access_key': 'f116083c6d4898ece2247ffc97e4af607451ca8d20755b7c',
        'service_id': 'ServiceId-ba6e3abe-76ec-4bd9-ad8f-50319827eb10'},
       'editor': {'access_key_id': '494a8d8e4e6243ec95c34d93e9707aac',
        'api_key': 'OXkChTvqwM8pr3aLtj6TOWg8S5-_WhqF_69V0yBxmuDd',
        'resource_key_crn': 'crn:v1:bluemix:public:cloud-object-storage:global:a/cec083d33451444c9bdfbd8a8e68291d:8615fcb3-642d-456e-9ff5-898709f54c54::',
        'secret_access_key': '346eca31e40fb9ce605aa3aa796afce4c6e11698a3eff91f',
        'service_id': 'ServiceId-19573d95-6a4a-4077-9860-ee9b59b12677'},
       'viewer': {'access_key_id': '7dd3d0bc444646e0b916a963e2ba1c1e',
        'api_key': 'wXbWg4dCzL_SKbx9dj6i-BKTUErSjIKZEhNndUi7-x_T',
        'resource_key_crn': 'crn:v1:bluemix:public:cloud-object-storage:global:a/cec083d33451444c9bdfbd8a8e68291d:8615fcb3-642d-456e-9ff5-898709f54c54::',
        'secret_access_key': 'eb13d8f232bad3b263cb051dd5377e64af1e21888d5743bd',
        'service_id': 'ServiceId-fa5b3014-94ab-4e41-9fa3-aec84496c7e8'}},
      'endpoint_url': 'https://s3.us-south.cloud-object-storage.appdomain.cloud',
      'guid': '8615fcb3-642d-456e-9ff5-898709f54c54',
      'resource_crn': 'crn:v1:bluemix:public:cloud-object-storage:global:a/cec083d33451444c9bdfbd8a8e68291d:8615fcb3-642d-456e-9ff5-898709f54c54::'},
     'type': 'bmcos_object_storage'}},
   'metadata': {'created_at': '2022-10-27T07:49:42.784Z',
    'creator_id': 'IBMid-663003ZMCA',
    'id': '0505f5e8-00b9-481c-aefc-438df31a63c9',
    'updated_at': '2022-10-27T07:50:05.422Z',
    'url': '/v2/spaces/0505f5e8-00b9-481c-aefc-438df31a63c9'}}]}
def guid_space_name(client,deploy):
  space = client.spaces.get_details()
  return (next(item for item in space['resources'] if item['entity']['name']==deploy)['metadata']['id'])
space_uid = guid_space_name(client,'Digit Recognition Deploy')
space_uid
'0505f5e8-00b9-481c-aefc-438df31a63c9'
client.set.default_space(space_uid)
'SUCCESS'
client.software_specifications.list()
-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
runtime-22.1-py3.9             12b83a17-24d8-5082-900f-0ab31fbfd3cb  base
scikit-learn_0.22-py3.6        154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base
default_r3.6                   1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base
pytorch-onnx_1.3-py3.6         1bc6029a-cc97-56da-b8e0-39c3880dbbe7  base
kernel-spark3.3-r3.6           1c9e5454-f216-59dd-a20e-474a5cdf5988  base
pytorch-onnx_rt22.1-py3.9-edt  1d362186-7ad5-5b59-8b6c-9d0880bde37f  base
tensorflow_2.1-py3.6           1eb25b84-d6ed-5dde-b6a5-3fbdf1665666  base
spark-mllib_3.2                20047f72-0a98-58c7-9ff5-a77b012eb8f5  base
tensorflow_2.4-py3.8-horovod   217c16f6-178f-56bf-824a-b19f20564c49  base
runtime-22.1-py3.9-cuda        26215f05-08c3-5a41-a1b0-da66306ce658  base
do_py3.8                       295addb5-9ef9-547e-9bf4-92ae3563e720  base
autoai-ts_3.8-py3.8            2aa0c932-798f-5ae9-abd6-15e0c2402fb5  base
tensorflow_1.15-py3.6          2b73a275-7cbf-420b-a912-eae7f436e0bc  base
kernel-spark3.3-py3.9          2b7961e2-e3b1-5a8c-a491-482c8368839a  base
pytorch_1.2-py3.6              2c8ef57d-2687-4b7d-acce-01f94976dac1  base
spark-mllib_2.3                2e51f700-bca0-4b0d-88dc-5c6791338875  base
pytorch-onnx_1.1-py3.6-edt     32983cea-3f32-4400-8965-dde874a8d67e  base
spark-mllib_3.0-py37           36507ebe-8770-55ba-ab2a-eafe787600e9  base
spark-mllib_2.4                390d21f8-e58b-4fac-9c55-d7ceda621326  base
xgboost_0.82-py3.6             39e31acd-5f30-41dc-ae44-60233c80306e  base
pytorch-onnx_1.2-py3.6-edt     40589d0e-7019-4e28-8daa-fb03b6f4fe12  base
default_r36py38                41c247d3-45f8-5a71-b065-8580229facf0  base
autoai-ts_rt22.1-py3.9         4269d26e-07ba-5d40-8f66-2d495b0c71f7  base
autoai-obm_3.0                 42b92e18-d9ab-567f-988a-4240ba1ed5f7  base
pmml-3.0_4.3                   493bcb95-16f1-5bc5-bee8-81b8af80e9c7  base
spark-mllib_2.4-r_3.6          49403dff-92e9-4c87-a3d7-a42d0021c095  base
xgboost_0.90-py3.6             4ff8d6c2-1343-4c18-85e1-689c965304d3  base
pytorch-onnx_1.1-py3.6         50f95b2a-bc16-43bb-bc94-b0bed208c60b  base
autoai-ts_3.9-py3.8            52c57136-80fa-572e-8728-a5e7cbb42cde  base
spark-mllib_2.4-scala_2.11     55a70f99-7320-4be5-9fb9-9edb5a443af5  base
spark-mllib_3.0                5c1b0ca2-4977-5c2e-9439-ffd44ea8ffe9  base
autoai-obm_2.0                 5c2e37fa-80b8-5e77-840f-d912469614ee  base
spss-modeler_18.1              5c3cad7e-507f-4b2a-a9a3-ab53a21dee8b  base
cuda-py3.8                     5d3232bf-c86b-5df4-a2cd-7bb870a1cd4e  base
autoai-kb_3.1-py3.7            632d4b22-10aa-5180-88f0-f52dfb6444d7  base
pytorch-onnx_1.7-py3.8         634d3cdc-b562-5bf9-a2d4-ea90a478456b  base
spark-mllib_2.3-r_3.6          6586b9e3-ccd6-4f92-900f-0f8cb2bd6f0c  base
tensorflow_2.4-py3.7           65e171d7-72d1-55d9-8ebb-f813d620c9bb  base
spss-modeler_18.2              687eddc9-028a-4117-b9dd-e57b36f1efa5  base
-----------------------------  ------------------------------------  ----
Note: Only first 50 records were displayed. To display more use 'limit' parameter.
software_space_uid = client.software_specifications.get_uid_by_name('tensorflow_rt22.1-py3.9')
software_space_uid
'acd9c798-6974-5d2f-a657-ce06e986df4d'
model_details = client.repository.store_model(model='digit-recognition.tar',meta_props={
    client.repository.ModelMetaNames.NAME:"CNN Digit recognition model repo",
    client.repository.ModelMetaNames.TYPE:"tensorflow_2.7",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_space_uid
})
model_details
{'entity': {'hybrid_pipeline_software_specs': [],
  'software_spec': {'id': 'acd9c798-6974-5d2f-a657-ce06e986df4d',
   'name': 'tensorflow_rt22.1-py3.9'},
  'type': 'tensorflow_2.7'},
 'metadata': {'created_at': '2022-10-29T18:18:15.410Z',
  'id': '00fe0261-bab5-4b80-8e70-d0f4a93f2811',
  'modified_at': '2022-10-29T18:18:19.003Z',
  'name': 'CNN Digit recognition model repo',
  'owner': 'IBMid-663003ZMCA',
  'resource_key': '56da2402-21a2-4e14-ad27-949232fa731e',
  'space_id': '0505f5e8-00b9-481c-aefc-438df31a63c9'},
 'system': {'warnings': []}}
model_id = client.repository.get_model_id(model_details)
model_id
'00fe0261-bab5-4b80-8e70-d0f4a93f2811'
client.repository.download(model_id,'DigitRecog_IBM_model.tar.gz')
Successfully saved model content to file: 'DigitRecog_IBM_model.tar.gz'
'/content/DigitRecog_IBM_model.tar.gz'